# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary -> appveyor.yml

# Adapt as necessary starting from here
branches:
  only:
    - master

environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    R_ARCH: x64
    USE_RTOOLS: true

  matrix:
    - R_VERSION: release

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_github jimhester/covr
  - travis-tool.sh install_github tlverse/origami
  - travis-tool.sh install_bioc BiocCheck
  - travis-tool.sh install_bioc BiocStyle
  - travis-tool.sh install_bioc BiocGenerics
  - travis-tool.sh install_bioc BiocParallel
  - travis-tool.sh install_bioc S4Vectors
  - travis-tool.sh install_bioc SummarizedExperiment
  - travis-tool.sh install_bioc GenomeInfoDbData
  - travis-tool.sh install_bioc GenomeInfoDb
  - travis-tool.sh install_bioc airway
  - travis-tool.sh install_bioc_deps

test_script:
  - travis-tool.sh run_tests

on_success:
  - Rscript -e "covr::codecov(line_exclusions = list('R/utils.R', 'R/get_summary.R', 'R/data.R', 'R/bioadaptest.R'))"
  - R CMD BiocCheck .

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
 - provider: Email
   to:
     - wcai@berkeley.edu
     - nh@nimahejazi.org
   subject: 'r-appveyor build {{status}}'
   message: "https://ci.appveyor.com/project/wilsoncai1992/adaptest"
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true

